### PR TITLE
User network usage feature

### PR DESCRIPTION
**Pull request by mgh12453**
Key Implementation Details:

- Utilizes Redis as the data store for recording user network usage.
- Adds tracking code in the DirectTCPIPHandler function to calculate and record the number of bytes read and written by users during their SSH sessions.
- Uses the HINCRBY Redis command to incrementally update the network usage for each user identified by their UUID.

Files afected:

- main.go: Modified to include the network usage tracking logic.
- generator.py: Modified to show user data usage when run with --list flag.

### CODE REVIEW

**Comment by erfan-khadem** [comment]
A few things to consider:

0. Fix the data structure. There is no need (at least for now) to have both the user's upload and download. Use a single number for each user. In addition, the structure should be:
  - "ssh-server:users-usage" is a hash structure (map)
  - Its keys are the users' uuid
  - the value of a key is the user's total usage (in bytes) = upload + download
1. Add a `reset` option to `get_client_usage` function in python. After reading the result, client's usage is decreased using the command `HINCRBY ssh-server:users-usage {client_uuid} -{client_usage}`. Take note of the negative sign and that the operation is atomic.
2. Use a simple `HGET` instead of `HINCRBY ... ... 0` :)
3. Add `--reset` and `--show-usage` options to the cli interface. `--reset` should have support for resetting all clients.

**Comment by mgh12453** [comment]
Thanks for notations.
Changes:

- Your described reviews have been considered.
- some design patterns optimizations. (task failed successfully)

New files:

- options.py: argument parsing logic moved to this file for better code architecture. note that Handler layer for arguments still is in the main.py for preventing circular imports and hard-reading code considerations.
- settings.py
- utils.py

**Comment by erfan-khadem** [comment]
Awesome! Thank you :clap:

**Comment by erfan-khadem** [comment]
Well, I had to merge using an external editor and it seems like GH didn't automatically set this PR as merged. So I will close it manually :)

**Pull request closed without merging**
